# Generated by Django 5.2 on 2025-05-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_options_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
