# Generated by Django 5.2 on 2025-07-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menu_product_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
